spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/ani_sphere?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: ik101145
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true

server:
  port: 9090

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

## 配置视频封面上传地址
file:
  upload-dir: D:/anivideo/uploads/user